# Generated by Django 3.2.4 on 2021-06-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('etat', models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('A', 'En attente')], default='A', max_length=1, verbose_name='Etat')),
                ('lien', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('j_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom')),
                ('domaine_xp', models.CharField(max_length=70, verbose_name="Domaine d'expertise")),
                ('type', models.CharField(choices=[('E', 'Expert'), ('P', 'Professeur')], max_length=1, verbose_name='Type')),
                ('tel_num', models.CharField(max_length=15, verbose_name='Numero de telephone')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Laureat',
            fields=[
                ('l_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StnPrst',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('laureat_nom', models.CharField(max_length=100, verbose_name='Nom Laureat')),
                ('dossier_lien', models.CharField(max_length=200, verbose_name='Lien Dossier')),
                ('dossier_etat', models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('A', 'En attente')], default='A', max_length=1, verbose_name='Etat Dossier')),
                ('theme', models.CharField(choices=[('ML', 'Machine Learning'), ('ST', "Systeme d'Information"), ('SQ', 'Systeme Informatique'), ('RS', 'Réseaux & Sécurité'), ('GL', 'Géni-Logiciel')], max_length=2, verbose_name='Thème')),
                ('type', models.CharField(choices=[('D', 'Doctorat'), ('H', 'Habilitation')], max_length=1, verbose_name='Type')),
                ('etat', models.CharField(choices=[('A', 'Autorisée'), ('R', 'Refusée'), ('N', 'Non définie'), ('C', 'Cloturée')], default='N', max_length=1, verbose_name='Etat')),
                ('sujet', models.CharField(max_length=150, verbose_name='Sujet')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('theme', models.CharField(choices=[('ML', 'Machine Learning'), ('ST', "Systeme d'Information"), ('SQ', 'Systeme Informatique'), ('RS', 'Réseaux & Sécurité'), ('GL', 'Géni-Logiciel')], max_length=2, verbose_name='Thème')),
                ('type', models.CharField(choices=[('D', 'Doctorat'), ('H', 'Habilitation')], max_length=1, verbose_name='Type')),
                ('etat', models.CharField(choices=[('A', 'Autorisée'), ('R', 'Refusée'), ('N', 'Non définie'), ('C', 'Cloturée')], default='N', max_length=1, verbose_name='Etat')),
                ('sujet', models.CharField(max_length=150, verbose_name='Sujet')),
                ('dossier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.dossier')),
                ('laureat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.laureat')),
            ],
        ),
        migrations.CreateModel(
            name='JuryStn',
            fields=[
                ('js_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('JU', 'Jury'), ('RP', 'Rapporteur'), ('DJ', 'Directeur des Jurys'), ('DR', 'Directeur des Rapporteurs')], max_length=2, verbose_name='Role')),
                ('jury_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.jury')),
                ('soutenance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.soutenance')),
            ],
        ),
    ]
